#!/usr/bin/env python3
"""The lab notebook, rendered from the bring-up log.

  python3 tools/lab-notebook.py            # write docs/lab-notebook.md
  python3 tools/lab-notebook.py --check    # exit 1 if it is not current

`tools/bringup.py` appends one JSON object per attempt to
`docs/lab-log.jsonl`. This turns that into the notebook. Nothing is
typed into the notebook by hand, for the same reason nothing else here
is: a second copy of a measurement drifts from the first, and the reader
has no way to tell which one is lying.

It renders every attempt, not the successful ones. A step that failed
twice before it held is the useful part of a lab notebook, and a
notebook that quietly shows only the last try is a worse record than no
notebook.

Photographs are embedded when the file is actually in `docs/lab/`, and
named as pending when it is not, so a notebook rendered before the
pictures are pushed carries no broken images and still says what is
missing. Re-run it after pushing them.
"""
import argparse
import importlib.util
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOG = ROOT / "docs" / "lab-log.jsonl"
OUT = ROOT / "docs" / "lab-notebook.md"

MARK = {"pass": "held", "fail": "did not hold", "skip": "skipped"}


def bringup_module():
    """The tool that runs the steps, for the things that belong to it
    rather than to the record: a step's title and the words for how a
    measurement was made are authored, and are read from the tool so a
    rename does not leave the notebook quoting an old one. The numbers,
    the times and the outcomes come from the log and are never touched."""
    sys.path.insert(0, str(ROOT / "tools"))
    from loadmod import load
    m = load(ROOT / "tools" / "bringup.py", "bringup")
    return m


def bringup_steps():
    """The steps, out of the tool that runs them. One fact, one place: a
    second copy of the build order here would drift from the one that is
    actually executed, and the reader could not tell which was lying."""
    sys.path.insert(0, str(ROOT / "tools"))
    from loadmod import load
    m = load(ROOT / "tools" / "bringup.py", "bringup")
    return m.STEPS

# Values worth a row of their own, in the order they read best, with the
# unit the tool records them in.
UNITS = {
    "latch_high_us": ("latch pulse, high", "us"), "clock_low_us": ("clock pulse, low", "us"),
    "clock_period_us": ("between clocks", "us"), "latch_period_ms": ("between polls", "ms"),
    "polls_per_s": ("polls per second", ""), "latches_seen": ("latches in the record", ""),
    "clocks_per_latch_mode": ("clocks per poll", ""), "polls": ("polls logged", ""),
    "supply_v": ("the supply lead", "V"), "out0_idle_v": ("OUT0 idle", "V"),
    "clk_idle_v": ("CLK idle", "V"), "d0_idle_v": ("D0 idle", "V"),
    "pin7_v": ("port pin 7, the +5V rail", "V"), "pin3_v": ("port pin 3, OUT0 idle", "V"),
    "pin2_v": ("port pin 2, CLK idle", "V"), "pin4_v": ("port pin 4, D0 idle", "V"),
    "qa_v": ("595 QA, not pressed", "V"), "qd_v": ("595 QD, pressed", "V"),
    "pulled_up_v": ("the reset pad, pulled up", "V"), "eight_fraction": ("polls with eight clocks", ""),
    "latch_high_cycles": ("latch high, in 2A03 cycles", ""), "clock_period_cycles": ("between clocks, in 2A03 cycles", ""),
}


def read_log():
    if not LOG.exists():
        return []
    out = []
    for line in LOG.read_text().splitlines():
        line = line.strip()
        if line:
            try:
                out.append(json.loads(line))
            except json.JSONDecodeError:
                pass
    return out


def value_rows(data):
    rows = []
    for k, (label, unit) in UNITS.items():
        if k in data and isinstance(data[k], (int, float)):
            v = data[k]
            s = f"{v:.3f}".rstrip("0").rstrip(".") if isinstance(v, float) else str(v)
            rows.append((label, f"{s} {unit}".strip()))
    return rows


def render(entries):
    # A rehearsal is the tool being exercised against tools/fake-bridge.py
    # and the like. It is not bench work and must never be counted as it,
    # but it is worth saying it happened.
    rehearsals = [e for e in entries if e.get("rehearsal")]
    entries = [e for e in entries if not e.get("rehearsal")]
    b = bringup_module()
    titles = {st["id"]: st["title"] for st in b.STEPS}
    methods = getattr(b, "METHODS", {})
    steps = {}
    for e in entries:
        e = dict(e, title=titles.get(e["step"], e["title"]))
        steps.setdefault(e["step"], []).append(e)
    order = sorted(steps, key=lambda s: [int(x) for x in s.split(".")])

    L = []
    L.append("# Lab notebook: building the bench")
    L.append("")
    L.append("Generated by `tools/lab-notebook.py` from `docs/lab-log.jsonl`,")
    L.append("which `tools/bringup.py` appends to as each step is attempted.")
    L.append("Nothing in it is typed by hand. Every attempt is shown, including")
    L.append("the ones that failed, because a step that took three tries is the")
    L.append("part of a notebook worth keeping.")
    L.append("")
    L.append("The build is v1b, the bridge on an Arduino UNO with everything at")
    L.append("5 V (`bench-v1b-uno.md`). The steps and their checks are in")
    L.append("`tools/bringup.py`, which is the procedure as well as the record:")
    L.append("run it and it walks the build, measuring at each stop.")
    L.append("")
    if rehearsals:
        when = sorted(e["at"][:10] for e in rehearsals)
        L.append(f"Before any of it touched hardware the tool was rehearsed against")
        L.append(f"stand-ins, {len(rehearsals)} attempts between {when[0]} and {when[-1]}.")
        L.append("Those are in the log, marked, and are not counted below.")
        L.append("")

    if not entries:
        steps = bringup_steps()
        L.append("## Nothing has been built yet")
        L.append("")
        L.append("No bench work is logged. The bench exists as a schematic, a pin")
        L.append("table and a sketch that compiles, and no part of it has been")
        L.append("wired. The steps below are what the tool will walk; each one")
        L.append("ends in a measurement, and the result appears here when it runs.")
        L.append("")
        stage = None
        for st in steps:
            if st["stage"] != stage:
                stage = st["stage"]
                if L and L[-1] != "":
                    L.append("")
                L.append(f"**{stage}**")
                L.append("")
            L.append(f"- **{st['id']}** {st['title']}")
            if st["replaces"]:
                L.append(f"  Answers: {st['replaces']}.")
        L.append("")
        L.append("Start with:")
        L.append("")
        L.append("```")
        L.append(f"python3 tools/bringup.py --list      # the {len(steps)} steps")
        L.append("python3 tools/bringup.py             # from where you left off")
        L.append("```")
        L.append("")
        return "\n".join(L) + "\n"

    held = sum(1 for s in order if steps[s][-1]["state"] == "pass")
    attempts = len(entries)
    L.append("## Where the build stands")
    L.append("")
    L.append(f"{held} of {len(order)} attempted steps hold, over {attempts} attempts.")
    L.append("")
    L.append("| step | what it proves | attempts | state |")
    L.append("|---|---|---|---|")
    for s in order:
        e = steps[s][-1]
        L.append(f"| {s} | {e['title']} | {len(steps[s])} | {MARK[e['state']]} |")
    L.append("")

    stage = None
    for s in order:
        e = steps[s][-1]
        if e.get("stage") != stage:
            stage = e.get("stage")
            L.append(f"## {stage}")
            L.append("")
        L.append(f"### {s}  {e['title']}")
        L.append("")
        if e.get("replaces"):
            L.append(f"Answers: {e['replaces']}.")
            L.append("")
        for i, a in enumerate(steps[s], 1):
            when = a["at"].replace("T", " ")
            lead = f"**{when}**" if len(steps[s]) == 1 else f"**Attempt {i}, {when}**"
            L.append(f"{lead}: {MARK[a['state']]}. {a['summary']}")
            L.append("")
            st = a.get("data", {}).get("console_state")
            if st and st != "not recorded":
                L.append(f"On screen: {st}.")
                L.append("")
            rows = value_rows(a.get("data", {}))
            if rows:
                L.append("| | |")
                L.append("|---|---|")
                for label, v in rows:
                    L.append(f"| {label} | {v} |")
                L.append("")
            hist = a.get("data", {}).get("hist") or a.get("data", {}).get("clocks_per_latch_hist")
            if hist:
                pairs = ", ".join(f"{k} clocks on {v} polls" for k, v in sorted(hist.items(), key=lambda kv: int(kv[0])))
                L.append(f"Clocks per poll: {pairs}.")
                L.append("")
            m = a.get("data", {}).get("map")
            if m:
                meth = a.get("data", {}).get("method")
                if meth:
                    L.append(f"Method: {methods.get(meth, meth)}.")
                    L.append("")
                # A breakout spliced onto the harness gets its own column
                # rather than its own table: it is the same seven pins,
                # and two tables of the same pins is how a reader ends up
                # comparing the wrong rows.
                bo = a.get("data", {}).get("breakout") or {}
                head = "| port pin | signal | harness |" + (" breakout lead |" if bo else "")
                L.append(head if bo else "| port pin | signal | wire |")
                L.append("|---|---|---|---|" if bo else "|---|---|---|")
                for k in sorted(m, key=lambda x: int(x[3:])):
                    c = m[k]["colour"] or "not rung out"
                    row = f"| {k[3:]} | {m[k]['name']} | {c} |"
                    if bo:
                        bc = (bo.get(k) or {}).get("colour") or ""
                        if bc.strip().lower() in ("", "nc", "none", "-", "skip", "s"):
                            bc = "not brought out"
                        row += f" {bc} |"
                    L.append(row)
                L.append("")
                for colour, pins in a.get("data", {}).get("shared", []):
                    ps = " and ".join(str(x) for x in pins)
                    L.append(f"Pins {ps} are the same colour on the breakout, both {colour}. "
                             "They were told apart with the meter, from the board header.")
                    L.append("")
                if a.get("data", {}).get("supply_out") is False:
                    L.append("The +5 V pin is not brought out to the breakout, so the supply "
                             "reading in step 1.2 is taken at the port housing or the board header.")
                    L.append("")
            for p in a.get("photos", []):
                name = Path(p["file"]).name
                if (ROOT / p["file"]).exists():
                    L.append(f"![{e['title']}](lab/{name})")
                else:
                    L.append(f"Photograph pending: `{p['file']}`.")
                L.append("")
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if docs/lab-notebook.md is not what this writes")
    a = ap.parse_args()
    text = render(read_log())
    if a.check:
        if not OUT.exists() or OUT.read_text() != text:
            print(f"{OUT} is not current: run python3 tools/lab-notebook.py")
            return 1
        print(f"{OUT} is current")
        return 0
    OUT.write_text(text)
    n = len(read_log())
    print(f"wrote {OUT.relative_to(ROOT)} from {n} logged attempt(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
